### PR TITLE
Is the server running?

### PR DESCRIPTION
**Pull request by with-a-k**
@stevekinney I feel like this should be working, but console.logging isn't producing anything.

### CODE REVIEW

**Comment by with-a-k** [comment]
wait, got it

**Comment by with-a-k** [comment]
although now I'm not getting anything other than "undefined" as messages from the client.

**Comment by stevekinney** [comment]
What did you send as the body of the message?

**Comment by with-a-k** [comment]
Oh, whoops. I missed that you'd gotten back, and in the meantime I figured it out.

**Pull request merged**
